/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FirewallRulePort } from './FirewallRulePort';
import {
    FirewallRulePortFromJSON,
    FirewallRulePortFromJSONTyped,
    FirewallRulePortToJSON,
} from './FirewallRulePort';

/**
 * A firewall rule applied to a workload pool.
 * @export
 * @interface FirewallRule
 */
export interface FirewallRule {
    /**
     * The protocol to allow.
     * @type {string}
     * @memberof FirewallRule
     */
    protocol: FirewallRuleProtocolEnum;
    /**
     * 
     * @type {FirewallRulePort}
     * @memberof FirewallRule
     */
    port: FirewallRulePort;
    /**
     * A list of CIDR blocks to allow, it might be any IPv4 or IPv6 in CIDR notation.
     * @type {Array<string>}
     * @memberof FirewallRule
     */
    cidr: Array<string>;
}


/**
 * @export
 */
export const FirewallRuleProtocolEnum = {
    Tcp: 'tcp',
    Udp: 'udp'
} as const;
export type FirewallRuleProtocolEnum = typeof FirewallRuleProtocolEnum[keyof typeof FirewallRuleProtocolEnum];


/**
 * Check if a given object implements the FirewallRule interface.
 */
export function instanceOfFirewallRule(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "protocol" in value;
    isInstance = isInstance && "port" in value;
    isInstance = isInstance && "cidr" in value;

    return isInstance;
}

export function FirewallRuleFromJSON(json: any): FirewallRule {
    return FirewallRuleFromJSONTyped(json, false);
}

export function FirewallRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): FirewallRule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'protocol': json['protocol'],
        'port': FirewallRulePortFromJSON(json['port']),
        'cidr': json['cidr'],
    };
}

export function FirewallRuleToJSON(value?: FirewallRule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'protocol': value.protocol,
        'port': FirewallRulePortToJSON(value.port),
        'cidr': value.cidr,
    };
}

