/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What type of machine the image is for.
 * @export
 */
export const ImageVirtualization = {
    Virtualized: 'virtualized',
    Baremetal: 'baremetal',
    Any: 'any'
} as const;
export type ImageVirtualization = typeof ImageVirtualization[keyof typeof ImageVirtualization];


export function ImageVirtualizationFromJSON(json: any): ImageVirtualization {
    return ImageVirtualizationFromJSONTyped(json, false);
}

export function ImageVirtualizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageVirtualization {
    return json as ImageVirtualization;
}

export function ImageVirtualizationToJSON(value?: ImageVirtualization | null): any {
    return value as any;
}

