/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A public IP allocation settings.
 * @export
 * @interface PublicIPAllocation
 */
export interface PublicIPAllocation {
    /**
     * Enable public IP allocation.
     * @type {boolean}
     * @memberof PublicIPAllocation
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the PublicIPAllocation interface.
 */
export function instanceOfPublicIPAllocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabled" in value;

    return isInstance;
}

export function PublicIPAllocationFromJSON(json: any): PublicIPAllocation {
    return PublicIPAllocationFromJSONTyped(json, false);
}

export function PublicIPAllocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicIPAllocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
    };
}

export function PublicIPAllocationToJSON(value?: PublicIPAllocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}

