/* tslint:disable */
/* eslint-disable */
/**
 * Compute Service API
 * The Compute Service API provides services that allows provisioning and life cycle management of Compute clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RegionFeatures } from './RegionFeatures';
import {
    RegionFeaturesFromJSON,
    RegionFeaturesFromJSONTyped,
    RegionFeaturesToJSON,
} from './RegionFeatures';
import type { RegionKubernetes } from './RegionKubernetes';
import {
    RegionKubernetesFromJSON,
    RegionKubernetesFromJSONTyped,
    RegionKubernetesToJSON,
} from './RegionKubernetes';
import type { RegionType } from './RegionType';
import {
    RegionTypeFromJSON,
    RegionTypeFromJSONTyped,
    RegionTypeToJSON,
} from './RegionType';

/**
 * Information about the region.
 * @export
 * @interface RegionSpec
 */
export interface RegionSpec {
    /**
     * 
     * @type {RegionType}
     * @memberof RegionSpec
     */
    type: RegionType;
    /**
     * 
     * @type {RegionKubernetes}
     * @memberof RegionSpec
     */
    kubernetes?: RegionKubernetes;
    /**
     * 
     * @type {RegionFeatures}
     * @memberof RegionSpec
     */
    features: RegionFeatures;
}

/**
 * Check if a given object implements the RegionSpec interface.
 */
export function instanceOfRegionSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "features" in value;

    return isInstance;
}

export function RegionSpecFromJSON(json: any): RegionSpec {
    return RegionSpecFromJSONTyped(json, false);
}

export function RegionSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': RegionTypeFromJSON(json['type']),
        'kubernetes': !exists(json, 'kubernetes') ? undefined : RegionKubernetesFromJSON(json['kubernetes']),
        'features': RegionFeaturesFromJSON(json['features']),
    };
}

export function RegionSpecToJSON(value?: RegionSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': RegionTypeToJSON(value.type),
        'kubernetes': RegionKubernetesToJSON(value.kubernetes),
        'features': RegionFeaturesToJSON(value.features),
    };
}

