/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters. The API is logically composed of authentication services, platform provider specific calls to get a set of resource types that can be then used by abstract Kubernetes Service resources to create and manage Kubernetes clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApplicationSpec } from './ApplicationSpec';
import {
    ApplicationSpecFromJSON,
    ApplicationSpecFromJSONTyped,
    ApplicationSpecToJSON,
} from './ApplicationSpec';
import type { ResourceReadMetadata } from './ResourceReadMetadata';
import {
    ResourceReadMetadataFromJSON,
    ResourceReadMetadataFromJSONTyped,
    ResourceReadMetadataToJSON,
} from './ResourceReadMetadata';

/**
 * 
 * @export
 * @interface ApplicationRead
 */
export interface ApplicationRead {
    /**
     * 
     * @type {ResourceReadMetadata}
     * @memberof ApplicationRead
     */
    metadata: ResourceReadMetadata;
    /**
     * 
     * @type {ApplicationSpec}
     * @memberof ApplicationRead
     */
    spec: ApplicationSpec;
}

/**
 * Check if a given object implements the ApplicationRead interface.
 */
export function instanceOfApplicationRead(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function ApplicationReadFromJSON(json: any): ApplicationRead {
    return ApplicationReadFromJSONTyped(json, false);
}

export function ApplicationReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ResourceReadMetadataFromJSON(json['metadata']),
        'spec': ApplicationSpecFromJSON(json['spec']),
    };
}

export function ApplicationReadToJSON(value?: ApplicationRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceReadMetadataToJSON(value.metadata),
        'spec': ApplicationSpecToJSON(value.spec),
    };
}

