/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters. The API is logically composed of authentication services, platform provider specific calls to get a set of resource types that can be then used by abstract Kubernetes Service resources to create and manage Kubernetes clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterManagerMetadata } from './ClusterManagerMetadata';
import {
    ClusterManagerMetadataFromJSON,
    ClusterManagerMetadataFromJSONTyped,
    ClusterManagerMetadataToJSON,
} from './ClusterManagerMetadata';
import type { ClusterManagerSpec } from './ClusterManagerSpec';
import {
    ClusterManagerSpecFromJSON,
    ClusterManagerSpecFromJSONTyped,
    ClusterManagerSpecToJSON,
} from './ClusterManagerSpec';

/**
 * A cluster manager.
 * @export
 * @interface ClusterManager
 */
export interface ClusterManager {
    /**
     * 
     * @type {ClusterManagerMetadata}
     * @memberof ClusterManager
     */
    metadata: ClusterManagerMetadata;
    /**
     * 
     * @type {ClusterManagerSpec}
     * @memberof ClusterManager
     */
    spec: ClusterManagerSpec;
}

/**
 * Check if a given object implements the ClusterManager interface.
 */
export function instanceOfClusterManager(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function ClusterManagerFromJSON(json: any): ClusterManager {
    return ClusterManagerFromJSONTyped(json, false);
}

export function ClusterManagerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterManager {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ClusterManagerMetadataFromJSON(json['metadata']),
        'spec': ClusterManagerSpecFromJSON(json['spec']),
    };
}

export function ClusterManagerToJSON(value?: ClusterManager | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ClusterManagerMetadataToJSON(value.metadata),
        'spec': ClusterManagerSpecToJSON(value.spec),
    };
}

