/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters. The API is logically composed of authentication services, platform provider specific calls to get a set of resource types that can be then used by abstract Kubernetes Service resources to create and manage Kubernetes clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ControlPlane } from './ControlPlane';
import {
    ControlPlaneFromJSON,
    ControlPlaneFromJSONTyped,
    ControlPlaneToJSON,
} from './ControlPlane';

/**
 * A list of control planes.
 * @export
 * @interface ControlPlanes
 */
export interface ControlPlanes extends Array<ControlPlane> {
}

/**
 * Check if a given object implements the ControlPlanes interface.
 */
export function instanceOfControlPlanes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ControlPlanesFromJSON(json: any): ControlPlanes {
    return ControlPlanesFromJSONTyped(json, false);
}

export function ControlPlanesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControlPlanes {
    return json;
}

export function ControlPlanesToJSON(value?: ControlPlanes | null): any {
    return value;
}

