/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters. The API is logically composed of authentication services, platform provider specific calls to get a set of resource types that can be then used by abstract Kubernetes Service resources to create and manage Kubernetes clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OpenstackImage } from './OpenstackImage';
import {
    OpenstackImageFromJSON,
    OpenstackImageFromJSONTyped,
    OpenstackImageToJSON,
} from './OpenstackImage';

/**
 * A list of OpenStack images that are compatible with this platform.
 * @export
 * @interface OpenstackImages
 */
export interface OpenstackImages extends Array<OpenstackImage> {
}

/**
 * Check if a given object implements the OpenstackImages interface.
 */
export function instanceOfOpenstackImages(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenstackImagesFromJSON(json: any): OpenstackImages {
    return OpenstackImagesFromJSONTyped(json, false);
}

export function OpenstackImagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenstackImages {
    return json;
}

export function OpenstackImagesToJSON(value?: OpenstackImages | null): any {
    return value;
}

