/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters. The API is logically composed of authentication services, platform provider specific calls to get a set of resource types that can be then used by abstract Kubernetes Service resources to create and manage Kubernetes clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An OpenStack volume.
 * @export
 * @interface OpenstackVolume
 */
export interface OpenstackVolume {
    /**
     * Disk size in GiB.
     * @type {number}
     * @memberof OpenstackVolume
     */
    size: number;
    /**
     * Volume availability zone. Overrides the cluster default.
     * @type {string}
     * @memberof OpenstackVolume
     */
    availabilityZone?: string;
}

/**
 * Check if a given object implements the OpenstackVolume interface.
 */
export function instanceOfOpenstackVolume(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "size" in value;

    return isInstance;
}

export function OpenstackVolumeFromJSON(json: any): OpenstackVolume {
    return OpenstackVolumeFromJSONTyped(json, false);
}

export function OpenstackVolumeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenstackVolume {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'size': json['size'],
        'availabilityZone': !exists(json, 'availabilityZone') ? undefined : json['availabilityZone'],
    };
}

export function OpenstackVolumeToJSON(value?: OpenstackVolume | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'size': value.size,
        'availabilityZone': value.availabilityZone,
    };
}

