/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters. The API is logically composed of authentication services, platform provider specific calls to get a set of resource types that can be then used by abstract Kubernetes Service resources to create and manage Kubernetes clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A resources's metadata
 * @export
 * @interface ResourceMetadata
 */
export interface ResourceMetadata {
    /**
     * Where the resource is related to a project, this is populated.
     * @type {string}
     * @memberof ResourceMetadata
     */
    project?: string;
    /**
     * Where the resource is scoped to a control plane, this is populated.
     * @type {string}
     * @memberof ResourceMetadata
     */
    controlplane?: string;
    /**
     * Where the resource is scoped to a region, this is populated,
     * @type {string}
     * @memberof ResourceMetadata
     */
    region?: string;
    /**
     * The time the resource was created.
     * @type {Date}
     * @memberof ResourceMetadata
     */
    creationTime: Date;
    /**
     * The time the resource was deleted.
     * @type {Date}
     * @memberof ResourceMetadata
     */
    deletionTime?: Date;
    /**
     * The current status of the resource. Intially the status will be "Unknown" until
     * the resource is reconciled by the relevant controller. It then will transition to
     * "Provisioning" and will be ready for use when it changes to "Provisioned". The status
     * will also transition to the "Provisioning" status during an update. The
     * status will change to "Deprovisioning" when a delete request is being processed.
     * It may also change to "Error" if an unexpected error occurred during any operation.
     * Errors may be transient.
     * @type {string}
     * @memberof ResourceMetadata
     */
    status: string;
}

/**
 * Check if a given object implements the ResourceMetadata interface.
 */
export function instanceOfResourceMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "creationTime" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ResourceMetadataFromJSON(json: any): ResourceMetadata {
    return ResourceMetadataFromJSONTyped(json, false);
}

export function ResourceMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'project': !exists(json, 'project') ? undefined : json['project'],
        'controlplane': !exists(json, 'controlplane') ? undefined : json['controlplane'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'creationTime': (new Date(json['creationTime'])),
        'deletionTime': !exists(json, 'deletionTime') ? undefined : (new Date(json['deletionTime'])),
        'status': json['status'],
    };
}

export function ResourceMetadataToJSON(value?: ResourceMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'project': value.project,
        'controlplane': value.controlplane,
        'region': value.region,
        'creationTime': (value.creationTime.toISOString()),
        'deletionTime': value.deletionTime === undefined ? undefined : (value.deletionTime.toISOString()),
        'status': value.status,
    };
}

