/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters. The API is logically composed of authentication services, platform provider specific calls to get a set of resource types that can be then used by abstract Kubernetes Service resources to create and manage Kubernetes clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A distribution name.
 * @export
 */
export const OsDistro = {
    Rocky: 'rocky',
    Ubuntu: 'ubuntu'
} as const;
export type OsDistro = typeof OsDistro[keyof typeof OsDistro];


export function OsDistroFromJSON(json: any): OsDistro {
    return OsDistroFromJSONTyped(json, false);
}

export function OsDistroFromJSONTyped(json: any, ignoreDiscriminator: boolean): OsDistro {
    return json as OsDistro;
}

export function OsDistroToJSON(value?: OsDistro | null): any {
    return value as any;
}

