/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters. The API is logically composed of authentication services, platform provider specific calls to get a set of resource types that can be then used by abstract Kubernetes Service resources to create and manage Kubernetes clusters. Requests must specify the HTML content type header.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Region specific information when the type is kubernetes.
 * @export
 * @interface RegionKubernetes
 */
export interface RegionKubernetes {
    /**
     * The region's base64 encoded Kubernetes configuration file.
     * @type {string}
     * @memberof RegionKubernetes
     */
    kubeconfig: string;
}

/**
 * Check if a given object implements the RegionKubernetes interface.
 */
export function instanceOfRegionKubernetes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kubeconfig" in value;

    return isInstance;
}

export function RegionKubernetesFromJSON(json: any): RegionKubernetes {
    return RegionKubernetesFromJSONTyped(json, false);
}

export function RegionKubernetesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionKubernetes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kubeconfig': json['kubeconfig'],
    };
}

export function RegionKubernetesToJSON(value?: RegionKubernetes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kubeconfig': value.kubeconfig,
    };
}

