/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VirtualKubernetesClusterWorkloadPool } from './VirtualKubernetesClusterWorkloadPool';
import {
    VirtualKubernetesClusterWorkloadPoolFromJSON,
    VirtualKubernetesClusterWorkloadPoolFromJSONTyped,
    VirtualKubernetesClusterWorkloadPoolToJSON,
} from './VirtualKubernetesClusterWorkloadPool';

/**
 * Virtual Kubernetes cluster creation parameters.
 * @export
 * @interface VirtualKubernetesClusterSpec
 */
export interface VirtualKubernetesClusterSpec {
    /**
     * The region to provision the cluster in.
     * @type {string}
     * @memberof VirtualKubernetesClusterSpec
     */
    regionId: string;
    /**
     * A set of virtual workload pools.
     * @type {Array<VirtualKubernetesClusterWorkloadPool>}
     * @memberof VirtualKubernetesClusterSpec
     */
    workloadPools: Array<VirtualKubernetesClusterWorkloadPool>;
}

/**
 * Check if a given object implements the VirtualKubernetesClusterSpec interface.
 */
export function instanceOfVirtualKubernetesClusterSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "regionId" in value;
    isInstance = isInstance && "workloadPools" in value;

    return isInstance;
}

export function VirtualKubernetesClusterSpecFromJSON(json: any): VirtualKubernetesClusterSpec {
    return VirtualKubernetesClusterSpecFromJSONTyped(json, false);
}

export function VirtualKubernetesClusterSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): VirtualKubernetesClusterSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionId': json['regionId'],
        'workloadPools': ((json['workloadPools'] as Array<any>).map(VirtualKubernetesClusterWorkloadPoolFromJSON)),
    };
}

export function VirtualKubernetesClusterSpecToJSON(value?: VirtualKubernetesClusterSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'regionId': value.regionId,
        'workloadPools': ((value.workloadPools as Array<any>).map(VirtualKubernetesClusterWorkloadPoolToJSON)),
    };
}

