/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Service API
 * The Kubernetes Service API provides services that allows provisioning and life cycle management of Kubernetes clusters.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';
import type { VirtualKubernetesClusterSpec } from './VirtualKubernetesClusterSpec';
import {
    VirtualKubernetesClusterSpecFromJSON,
    VirtualKubernetesClusterSpecFromJSONTyped,
    VirtualKubernetesClusterSpecToJSON,
} from './VirtualKubernetesClusterSpec';

/**
 * Virtual Kubernetes cluster read.
 * @export
 * @interface VirtualKubernetesClusterRead
 */
export interface VirtualKubernetesClusterRead {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof VirtualKubernetesClusterRead
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {VirtualKubernetesClusterSpec}
     * @memberof VirtualKubernetesClusterRead
     */
    spec: VirtualKubernetesClusterSpec;
}

/**
 * Check if a given object implements the VirtualKubernetesClusterRead interface.
 */
export function instanceOfVirtualKubernetesClusterRead(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function VirtualKubernetesClusterReadFromJSON(json: any): VirtualKubernetesClusterRead {
    return VirtualKubernetesClusterReadFromJSONTyped(json, false);
}

export function VirtualKubernetesClusterReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): VirtualKubernetesClusterRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': VirtualKubernetesClusterSpecFromJSON(json['spec']),
    };
}

export function VirtualKubernetesClusterReadToJSON(value?: VirtualKubernetesClusterRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': VirtualKubernetesClusterSpecToJSON(value.spec),
    };
}

