/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GpuSpec } from './GpuSpec';
import {
    GpuSpecFromJSON,
    GpuSpecFromJSONTyped,
    GpuSpecToJSON,
} from './GpuSpec';

/**
 * A flavor.
 * @export
 * @interface FlavorSpec
 */
export interface FlavorSpec {
    /**
     * Whether the flavor is for a dedicated machine.
     * @type {boolean}
     * @memberof FlavorSpec
     */
    baremetal?: boolean;
    /**
     * The number of CPUs.
     * @type {number}
     * @memberof FlavorSpec
     */
    cpus: number;
    /**
     * A free form CPU family description e.g. model number, architecture.
     * @type {string}
     * @memberof FlavorSpec
     */
    cpuFamily?: string;
    /**
     * The amount of memory in GiB.
     * @type {number}
     * @memberof FlavorSpec
     */
    memory: number;
    /**
     * The amount of ephemeral disk in GB.
     * @type {number}
     * @memberof FlavorSpec
     */
    disk: number;
    /**
     * 
     * @type {GpuSpec}
     * @memberof FlavorSpec
     */
    gpu?: GpuSpec;
}

/**
 * Check if a given object implements the FlavorSpec interface.
 */
export function instanceOfFlavorSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cpus" in value;
    isInstance = isInstance && "memory" in value;
    isInstance = isInstance && "disk" in value;

    return isInstance;
}

export function FlavorSpecFromJSON(json: any): FlavorSpec {
    return FlavorSpecFromJSONTyped(json, false);
}

export function FlavorSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlavorSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'baremetal': !exists(json, 'baremetal') ? undefined : json['baremetal'],
        'cpus': json['cpus'],
        'cpuFamily': !exists(json, 'cpuFamily') ? undefined : json['cpuFamily'],
        'memory': json['memory'],
        'disk': json['disk'],
        'gpu': !exists(json, 'gpu') ? undefined : GpuSpecFromJSON(json['gpu']),
    };
}

export function FlavorSpecToJSON(value?: FlavorSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'baremetal': value.baremetal,
        'cpus': value.cpus,
        'cpuFamily': value.cpuFamily,
        'memory': value.memory,
        'disk': value.disk,
        'gpu': GpuSpecToJSON(value.gpu),
    };
}

