/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Everything an OpenStack client needs to function.
 * @export
 * @interface IdentitySpecOpenStack
 */
export interface IdentitySpecOpenStack {
    /**
     * The name of the cloud in the cloud config.
     * @type {string}
     * @memberof IdentitySpecOpenStack
     */
    cloud?: string;
    /**
     * A base64 encoded cloud config file.
     * @type {string}
     * @memberof IdentitySpecOpenStack
     */
    cloudConfig?: string;
    /**
     * User identitifer allocated for the infrastructure.
     * @type {string}
     * @memberof IdentitySpecOpenStack
     */
    userId?: string;
    /**
     * Project identifier allocated for the infrastructure.
     * @type {string}
     * @memberof IdentitySpecOpenStack
     */
    projectId?: string;
    /**
     * Server group identifier allocated for the intrastructure.
     * @type {string}
     * @memberof IdentitySpecOpenStack
     */
    serverGroupId?: string;
}

/**
 * Check if a given object implements the IdentitySpecOpenStack interface.
 */
export function instanceOfIdentitySpecOpenStack(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IdentitySpecOpenStackFromJSON(json: any): IdentitySpecOpenStack {
    return IdentitySpecOpenStackFromJSONTyped(json, false);
}

export function IdentitySpecOpenStackFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentitySpecOpenStack {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cloud': !exists(json, 'cloud') ? undefined : json['cloud'],
        'cloudConfig': !exists(json, 'cloudConfig') ? undefined : json['cloudConfig'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'projectId': !exists(json, 'projectId') ? undefined : json['projectId'],
        'serverGroupId': !exists(json, 'serverGroupId') ? undefined : json['serverGroupId'],
    };
}

export function IdentitySpecOpenStackToJSON(value?: IdentitySpecOpenStack | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cloud': value.cloud,
        'cloudConfig': value.cloudConfig,
        'userId': value.userId,
        'projectId': value.projectId,
        'serverGroupId': value.serverGroupId,
    };
}

