/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ImageGpu } from './ImageGpu';
import {
    ImageGpuFromJSON,
    ImageGpuFromJSONTyped,
    ImageGpuToJSON,
} from './ImageGpu';
import type { ImageVirtualization } from './ImageVirtualization';
import {
    ImageVirtualizationFromJSON,
    ImageVirtualizationFromJSONTyped,
    ImageVirtualizationToJSON,
} from './ImageVirtualization';
import type { SoftwareVersions } from './SoftwareVersions';
import {
    SoftwareVersionsFromJSON,
    SoftwareVersionsFromJSONTyped,
    SoftwareVersionsToJSON,
} from './SoftwareVersions';

/**
 * An image.
 * @export
 * @interface ImageSpec
 */
export interface ImageSpec {
    /**
     * 
     * @type {ImageVirtualization}
     * @memberof ImageSpec
     */
    virtualization: ImageVirtualization;
    /**
     * 
     * @type {SoftwareVersions}
     * @memberof ImageSpec
     */
    softwareVersions?: SoftwareVersions;
    /**
     * 
     * @type {ImageGpu}
     * @memberof ImageSpec
     */
    gpu?: ImageGpu;
}

/**
 * Check if a given object implements the ImageSpec interface.
 */
export function instanceOfImageSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "virtualization" in value;

    return isInstance;
}

export function ImageSpecFromJSON(json: any): ImageSpec {
    return ImageSpecFromJSONTyped(json, false);
}

export function ImageSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'virtualization': ImageVirtualizationFromJSON(json['virtualization']),
        'softwareVersions': !exists(json, 'softwareVersions') ? undefined : SoftwareVersionsFromJSON(json['softwareVersions']),
        'gpu': !exists(json, 'gpu') ? undefined : ImageGpuFromJSON(json['gpu']),
    };
}

export function ImageSpecToJSON(value?: ImageSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'virtualization': ImageVirtualizationToJSON(value.virtualization),
        'softwareVersions': SoftwareVersionsToJSON(value.softwareVersions),
        'gpu': ImageGpuToJSON(value.gpu),
    };
}

