/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';

/**
 * A list of images that are compatible with this platform.
 * @export
 * @interface Images
 */
export interface Images extends Array<Image> {
}

/**
 * Check if a given object implements the Images interface.
 */
export function instanceOfImages(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImagesFromJSON(json: any): Images {
    return ImagesFromJSONTyped(json, false);
}

export function ImagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Images {
    return json;
}

export function ImagesToJSON(value?: Images | null): any {
    return value;
}

