/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NetworkReadSpec } from './NetworkReadSpec';
import {
    NetworkReadSpecFromJSON,
    NetworkReadSpecFromJSONTyped,
    NetworkReadSpecToJSON,
} from './NetworkReadSpec';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';

/**
 * A network.
 * @export
 * @interface NetworkRead
 */
export interface NetworkRead {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof NetworkRead
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {NetworkReadSpec}
     * @memberof NetworkRead
     */
    spec: NetworkReadSpec;
}

/**
 * Check if a given object implements the NetworkRead interface.
 */
export function instanceOfNetworkRead(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function NetworkReadFromJSON(json: any): NetworkRead {
    return NetworkReadFromJSONTyped(json, false);
}

export function NetworkReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': NetworkReadSpecFromJSON(json['spec']),
    };
}

export function NetworkReadToJSON(value?: NetworkRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': NetworkReadSpecToJSON(value.spec),
    };
}

