/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A family of operating systems.  This typically defines the package format.
 * @export
 */
export const OsFamily = {
    Redhat: 'redhat',
    Debian: 'debian'
} as const;
export type OsFamily = typeof OsFamily[keyof typeof OsFamily];


export function OsFamilyFromJSON(json: any): OsFamily {
    return OsFamilyFromJSONTyped(json, false);
}

export function OsFamilyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OsFamily {
    return json as OsFamily;
}

export function OsFamilyToJSON(value?: OsFamily | null): any {
    return value as any;
}

