/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PhysicalNetworkSpec } from './PhysicalNetworkSpec';
import {
    PhysicalNetworkSpecFromJSON,
    PhysicalNetworkSpecFromJSONTyped,
    PhysicalNetworkSpecToJSON,
} from './PhysicalNetworkSpec';
import type { ProjectScopedResourceReadMetadata } from './ProjectScopedResourceReadMetadata';
import {
    ProjectScopedResourceReadMetadataFromJSON,
    ProjectScopedResourceReadMetadataFromJSONTyped,
    ProjectScopedResourceReadMetadataToJSON,
} from './ProjectScopedResourceReadMetadata';

/**
 * A physical network.
 * @export
 * @interface PhysicalNetworkRead
 */
export interface PhysicalNetworkRead {
    /**
     * 
     * @type {ProjectScopedResourceReadMetadata}
     * @memberof PhysicalNetworkRead
     */
    metadata: ProjectScopedResourceReadMetadata;
    /**
     * 
     * @type {PhysicalNetworkSpec}
     * @memberof PhysicalNetworkRead
     */
    spec: PhysicalNetworkSpec;
}

/**
 * Check if a given object implements the PhysicalNetworkRead interface.
 */
export function instanceOfPhysicalNetworkRead(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function PhysicalNetworkReadFromJSON(json: any): PhysicalNetworkRead {
    return PhysicalNetworkReadFromJSONTyped(json, false);
}

export function PhysicalNetworkReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhysicalNetworkRead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataFromJSON(json['metadata']),
        'spec': PhysicalNetworkSpecFromJSON(json['spec']),
    };
}

export function PhysicalNetworkReadToJSON(value?: PhysicalNetworkRead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ProjectScopedResourceReadMetadataToJSON(value.metadata),
        'spec': PhysicalNetworkSpecToJSON(value.spec),
    };
}

