/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './Tag';

/**
 * A phyical network's specification.
 * @export
 * @interface PhysicalNetworkSpec
 */
export interface PhysicalNetworkSpec {
    /**
     * A list of tags.
     * @type {Array<Tag>}
     * @memberof PhysicalNetworkSpec
     */
    tags?: Array<Tag>;
    /**
     * An IPv4 address prefix.
     * @type {string}
     * @memberof PhysicalNetworkSpec
     */
    prefix: string;
}

/**
 * Check if a given object implements the PhysicalNetworkSpec interface.
 */
export function instanceOfPhysicalNetworkSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "prefix" in value;

    return isInstance;
}

export function PhysicalNetworkSpecFromJSON(json: any): PhysicalNetworkSpec {
    return PhysicalNetworkSpecFromJSONTyped(json, false);
}

export function PhysicalNetworkSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhysicalNetworkSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': !exists(json, 'tags') ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
        'prefix': json['prefix'],
    };
}

export function PhysicalNetworkSpecToJSON(value?: PhysicalNetworkSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags === undefined ? undefined : ((value.tags as Array<any>).map(TagToJSON)),
        'prefix': value.prefix,
    };
}

