/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PhysicalNetworkSpecOpenstack } from './PhysicalNetworkSpecOpenstack';
import {
    PhysicalNetworkSpecOpenstackFromJSON,
    PhysicalNetworkSpecOpenstackFromJSONTyped,
    PhysicalNetworkSpecOpenstackToJSON,
} from './PhysicalNetworkSpecOpenstack';
import type { RegionType } from './RegionType';
import {
    RegionTypeFromJSON,
    RegionTypeFromJSONTyped,
    RegionTypeToJSON,
} from './RegionType';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './Tag';

/**
 * A phyical network's specification.
 * @export
 * @interface PhysicalNetworkReadSpec
 */
export interface PhysicalNetworkReadSpec {
    /**
     * A list of tags.
     * @type {Array<Tag>}
     * @memberof PhysicalNetworkReadSpec
     */
    tags?: Array<Tag>;
    /**
     * An IPv4 prefix for the network.
     * @type {string}
     * @memberof PhysicalNetworkReadSpec
     */
    prefix: string;
    /**
     * A list of IPv4 addresses.
     * @type {Array<string>}
     * @memberof PhysicalNetworkReadSpec
     */
    dnsNameservers: Array<string>;
    /**
     * 
     * @type {RegionType}
     * @memberof PhysicalNetworkReadSpec
     */
    type: RegionType;
    /**
     * The region an identity is provisioned in.
     * @type {string}
     * @memberof PhysicalNetworkReadSpec
     */
    regionId: string;
    /**
     * 
     * @type {PhysicalNetworkSpecOpenstack}
     * @memberof PhysicalNetworkReadSpec
     */
    openstack?: PhysicalNetworkSpecOpenstack;
}

/**
 * Check if a given object implements the PhysicalNetworkReadSpec interface.
 */
export function instanceOfPhysicalNetworkReadSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "prefix" in value;
    isInstance = isInstance && "dnsNameservers" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "regionId" in value;

    return isInstance;
}

export function PhysicalNetworkReadSpecFromJSON(json: any): PhysicalNetworkReadSpec {
    return PhysicalNetworkReadSpecFromJSONTyped(json, false);
}

export function PhysicalNetworkReadSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhysicalNetworkReadSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': !exists(json, 'tags') ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
        'prefix': json['prefix'],
        'dnsNameservers': json['dnsNameservers'],
        'type': RegionTypeFromJSON(json['type']),
        'regionId': json['regionId'],
        'openstack': !exists(json, 'openstack') ? undefined : PhysicalNetworkSpecOpenstackFromJSON(json['openstack']),
    };
}

export function PhysicalNetworkReadSpecToJSON(value?: PhysicalNetworkReadSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags === undefined ? undefined : ((value.tags as Array<any>).map(TagToJSON)),
        'prefix': value.prefix,
        'dnsNameservers': value.dnsNameservers,
        'type': RegionTypeToJSON(value.type),
        'regionId': value.regionId,
        'openstack': PhysicalNetworkSpecOpenstackToJSON(value.openstack),
    };
}

