/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceProvisioningStatus } from './ResourceProvisioningStatus';
import {
    ResourceProvisioningStatusFromJSON,
    ResourceProvisioningStatusFromJSONTyped,
    ResourceProvisioningStatusToJSON,
} from './ResourceProvisioningStatus';

/**
 * 
 * @export
 * @interface RegionScopedResourceMetadata
 */
export interface RegionScopedResourceMetadata {
    /**
     * A valid Kubenetes label value, typically used for resource names that can be
     * indexed in the database.
     * @type {string}
     * @memberof RegionScopedResourceMetadata
     */
    name: string;
    /**
     * The resource description, this optionally augments the name with more context.
     * @type {string}
     * @memberof RegionScopedResourceMetadata
     */
    description?: string;
    /**
     * The unique resource ID.
     * @type {string}
     * @memberof RegionScopedResourceMetadata
     */
    id: string;
    /**
     * The time the resource was created.
     * @type {Date}
     * @memberof RegionScopedResourceMetadata
     */
    creationTime: Date;
    /**
     * The user who created the resource.
     * @type {string}
     * @memberof RegionScopedResourceMetadata
     */
    createdBy?: string;
    /**
     * The time the resource was deleted.
     * @type {Date}
     * @memberof RegionScopedResourceMetadata
     */
    deletionTime?: Date;
    /**
     * 
     * @type {ResourceProvisioningStatus}
     * @memberof RegionScopedResourceMetadata
     */
    provisioningStatus: ResourceProvisioningStatus;
    /**
     * The organization identifier the resource belongs to.
     * @type {string}
     * @memberof RegionScopedResourceMetadata
     */
    organizationId: string;
    /**
     * The project identifier the resource belongs to.
     * @type {string}
     * @memberof RegionScopedResourceMetadata
     */
    projectId: string;
    /**
     * A region identifier.
     * @type {string}
     * @memberof RegionScopedResourceMetadata
     */
    regionId: string;
}

/**
 * Check if a given object implements the RegionScopedResourceMetadata interface.
 */
export function instanceOfRegionScopedResourceMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "creationTime" in value;
    isInstance = isInstance && "provisioningStatus" in value;
    isInstance = isInstance && "organizationId" in value;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "regionId" in value;

    return isInstance;
}

export function RegionScopedResourceMetadataFromJSON(json: any): RegionScopedResourceMetadata {
    return RegionScopedResourceMetadataFromJSONTyped(json, false);
}

export function RegionScopedResourceMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionScopedResourceMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': json['id'],
        'creationTime': (new Date(json['creationTime'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'deletionTime': !exists(json, 'deletionTime') ? undefined : (new Date(json['deletionTime'])),
        'provisioningStatus': ResourceProvisioningStatusFromJSON(json['provisioningStatus']),
        'organizationId': json['organizationId'],
        'projectId': json['projectId'],
        'regionId': json['regionId'],
    };
}

export function RegionScopedResourceMetadataToJSON(value?: RegionScopedResourceMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'id': value.id,
        'creationTime': (value.creationTime.toISOString()),
        'createdBy': value.createdBy,
        'deletionTime': value.deletionTime === undefined ? undefined : (value.deletionTime.toISOString()),
        'provisioningStatus': ResourceProvisioningStatusToJSON(value.provisioningStatus),
        'organizationId': value.organizationId,
        'projectId': value.projectId,
        'regionId': value.regionId,
    };
}

