/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A security group's specification.
 * @export
 * @interface SecurityGroupReadSpec
 */
export interface SecurityGroupReadSpec {
    /**
     * The region an identity is provisioned in.
     * @type {string}
     * @memberof SecurityGroupReadSpec
     */
    regionId: string;
}

/**
 * Check if a given object implements the SecurityGroupReadSpec interface.
 */
export function instanceOfSecurityGroupReadSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "regionId" in value;

    return isInstance;
}

export function SecurityGroupReadSpecFromJSON(json: any): SecurityGroupReadSpec {
    return SecurityGroupReadSpecFromJSONTyped(json, false);
}

export function SecurityGroupReadSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityGroupReadSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'regionId': json['regionId'],
    };
}

export function SecurityGroupReadSpecToJSON(value?: SecurityGroupReadSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'regionId': value.regionId,
    };
}

