/* tslint:disable */
/* eslint-disable */
/**
 * Region Service API
 * Cloud region discovery and routing service.  This is service not intended for direct access by end users.  Region related functionality is typically exposed by higher level services e.g. Compute and Kubernetes, that provide subsets of resources that are compatible with that service.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A security group.
 * @export
 * @interface ServerSecurityGroup
 */
export interface ServerSecurityGroup {
    /**
     * The security group ID.
     * @type {string}
     * @memberof ServerSecurityGroup
     */
    id: string;
}

/**
 * Check if a given object implements the ServerSecurityGroup interface.
 */
export function instanceOfServerSecurityGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ServerSecurityGroupFromJSON(json: any): ServerSecurityGroup {
    return ServerSecurityGroupFromJSONTyped(json, false);
}

export function ServerSecurityGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerSecurityGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ServerSecurityGroupToJSON(value?: ServerSecurityGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

