/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes Region Service API
 * Cloud region discovery and routing service.
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The server's public IP allocation.
 * @export
 * @interface ServerPublicIPAllocation
 */
export interface ServerPublicIPAllocation {
    /**
     * Whether to allocate a public IP.
     * @type {boolean}
     * @memberof ServerPublicIPAllocation
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the ServerPublicIPAllocation interface.
 */
export function instanceOfServerPublicIPAllocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabled" in value;

    return isInstance;
}

export function ServerPublicIPAllocationFromJSON(json: any): ServerPublicIPAllocation {
    return ServerPublicIPAllocationFromJSONTyped(json, false);
}

export function ServerPublicIPAllocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerPublicIPAllocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
    };
}

export function ServerPublicIPAllocationToJSON(value?: ServerPublicIPAllocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
    };
}

