/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An access control operation.
 * @export
 */
export const AclOperation = {
    Create: 'create',
    Read: 'read',
    Update: 'update',
    Delete: 'delete'
} as const;
export type AclOperation = typeof AclOperation[keyof typeof AclOperation];


export function AclOperationFromJSON(json: any): AclOperation {
    return AclOperationFromJSONTyped(json, false);
}

export function AclOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AclOperation {
    return json as AclOperation;
}

export function AclOperationToJSON(value?: AclOperation | null): any {
    return value as any;
}

