/* tslint:disable */
/* eslint-disable */
/**
 * Unikorn Identity API
 * The Unikorn Identity API provides an OIDC compliant interface for use with all Unikorn services and proxies.  As it\'s intended use is for multi-tenant cloud deployments it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Supported authentication methods.
 * @export
 */
export const AuthMethod = {
    Post: 'client_secret_post',
    Basic: 'client_secret_basic'
} as const;
export type AuthMethod = typeof AuthMethod[keyof typeof AuthMethod];


export function AuthMethodFromJSON(json: any): AuthMethod {
    return AuthMethodFromJSONTyped(json, false);
}

export function AuthMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMethod {
    return json as AuthMethod;
}

export function AuthMethodToJSON(value?: AuthMethod | null): any {
    return value as any;
}

