/* tslint:disable */
/* eslint-disable */
/**
 * Unikorn Identity API
 * The Unikorn Identity API provides an OIDC compliant interface for use with all Unikorn services and proxies.  As it\'s intended use is for multi-tenant cloud deployments it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
} from './Group';

/**
 * A list of groups.
 * @export
 * @interface Groups
 */
export interface Groups extends Array<Group> {
}

/**
 * Check if a given object implements the Groups interface.
 */
export function instanceOfGroups(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupsFromJSON(json: any): Groups {
    return GroupsFromJSONTyped(json, false);
}

export function GroupsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Groups {
    return json;
}

export function GroupsToJSON(value?: Groups | null): any {
    return value;
}

