/* tslint:disable */
/* eslint-disable */
/**
 * Unikorn Identity API
 * The Unikorn Identity API provides an OIDC compliant interface for use with all Unikorn services and proxies.  As it\'s intended use is for multi-tenant cloud deployments it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Oauth2ProviderType } from './Oauth2ProviderType';
import {
    Oauth2ProviderTypeFromJSON,
    Oauth2ProviderTypeFromJSONTyped,
    Oauth2ProviderTypeToJSON,
} from './Oauth2ProviderType';

/**
 * An oauth2 provider.
 * @export
 * @interface Oauth2ProviderCreate
 */
export interface Oauth2ProviderCreate {
    /**
     * A description of the provider.
     * @type {string}
     * @memberof Oauth2ProviderCreate
     */
    name: string;
    /**
     * 
     * @type {Oauth2ProviderType}
     * @memberof Oauth2ProviderCreate
     */
    type?: Oauth2ProviderType;
    /**
     * The name to display for the provider.
     * @type {string}
     * @memberof Oauth2ProviderCreate
     */
    displayName: string;
    /**
     * The OIDC issuer, typically where to perform auto discovery relative to.
     * @type {string}
     * @memberof Oauth2ProviderCreate
     */
    issuer: string;
    /**
     * The client identification, only shown for super admin or organization owned providers
     * that you are an admin for.
     * 
     * @type {string}
     * @memberof Oauth2ProviderCreate
     */
    clientID: string;
    /**
     * The client secret, only shown for super admin or organization owned providers
     * that you are an admin for.
     * 
     * @type {string}
     * @memberof Oauth2ProviderCreate
     */
    clientSecret?: string;
}

/**
 * Check if a given object implements the Oauth2ProviderCreate interface.
 */
export function instanceOfOauth2ProviderCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "displayName" in value;
    isInstance = isInstance && "issuer" in value;
    isInstance = isInstance && "clientID" in value;

    return isInstance;
}

export function Oauth2ProviderCreateFromJSON(json: any): Oauth2ProviderCreate {
    return Oauth2ProviderCreateFromJSONTyped(json, false);
}

export function Oauth2ProviderCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oauth2ProviderCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': !exists(json, 'type') ? undefined : Oauth2ProviderTypeFromJSON(json['type']),
        'displayName': json['displayName'],
        'issuer': json['issuer'],
        'clientID': json['clientID'],
        'clientSecret': !exists(json, 'clientSecret') ? undefined : json['clientSecret'],
    };
}

export function Oauth2ProviderCreateToJSON(value?: Oauth2ProviderCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': Oauth2ProviderTypeToJSON(value.type),
        'displayName': value.displayName,
        'issuer': value.issuer,
        'clientID': value.clientID,
        'clientSecret': value.clientSecret,
    };
}

