/* tslint:disable */
/* eslint-disable */
/**
 * Unikorn Identity API
 * The Unikorn Identity API provides an OIDC compliant interface for use with all Unikorn services and proxies.  As it\'s intended use is for multi-tenant cloud deployments it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GroupIDs } from './GroupIDs';
import {
    GroupIDsFromJSON,
    GroupIDsFromJSONTyped,
    GroupIDsToJSON,
} from './GroupIDs';

/**
 * A project.
 * @export
 * @interface ProjectSpec
 */
export interface ProjectSpec {
    /**
     * 
     * @type {string}
     * @memberof ProjectSpec
     */
    name: string;
    /**
     * 
     * @type {GroupIDs}
     * @memberof ProjectSpec
     */
    groupIDs?: GroupIDs;
}

/**
 * Check if a given object implements the ProjectSpec interface.
 */
export function instanceOfProjectSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProjectSpecFromJSON(json: any): ProjectSpec {
    return ProjectSpecFromJSONTyped(json, false);
}

export function ProjectSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'groupIDs': !exists(json, 'groupIDs') ? undefined : GroupIDsFromJSON(json['groupIDs']),
    };
}

export function ProjectSpecToJSON(value?: ProjectSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'groupIDs': GroupIDsToJSON(value.groupIDs),
    };
}

