/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A project.
 * @export
 * @interface ProjectSpec
 */
export interface ProjectSpec {
    /**
     * A list of group IDs.
     * @type {Array<string>}
     * @memberof ProjectSpec
     */
    groupIDs: Array<string>;
}

/**
 * Check if a given object implements the ProjectSpec interface.
 */
export function instanceOfProjectSpec(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "groupIDs" in value;

    return isInstance;
}

export function ProjectSpecFromJSON(json: any): ProjectSpec {
    return ProjectSpecFromJSONTyped(json, false);
}

export function ProjectSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSpec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupIDs': json['groupIDs'],
    };
}

export function ProjectSpecToJSON(value?: ProjectSpec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupIDs': value.groupIDs,
    };
}

