/* tslint:disable */
/* eslint-disable */
/**
 * Unikorn Identity API
 * The Unikorn Identity API provides an OIDC compliant interface for use with all Unikorn services and proxies.  As it\'s intended use is for multi-tenant cloud deployments it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A single quota.
 * @export
 * @interface Quota
 */
export interface Quota {
    /**
     * The kind of resource.
     * @type {string}
     * @memberof Quota
     */
    kind: string;
    /**
     * Tha amount of that resource.
     * @type {number}
     * @memberof Quota
     */
    quantity: number;
}

/**
 * Check if a given object implements the Quota interface.
 */
export function instanceOfQuota(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function QuotaFromJSON(json: any): Quota {
    return QuotaFromJSONTyped(json, false);
}

export function QuotaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Quota {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'quantity': json['quantity'],
    };
}

export function QuotaToJSON(value?: Quota | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'quantity': value.quantity,
    };
}

