/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { QuotaWrite } from './QuotaWrite';
import {
    QuotaWriteFromJSON,
    QuotaWriteFromJSONTyped,
    QuotaWriteToJSON,
} from './QuotaWrite';

/**
 * A list of quotas.
 * @export
 * @interface QuotasWrite
 */
export interface QuotasWrite {
    /**
     * A list of quotas.
     * @type {Array<QuotaWrite>}
     * @memberof QuotasWrite
     */
    quotas: Array<QuotaWrite>;
}

/**
 * Check if a given object implements the QuotasWrite interface.
 */
export function instanceOfQuotasWrite(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "quotas" in value;

    return isInstance;
}

export function QuotasWriteFromJSON(json: any): QuotasWrite {
    return QuotasWriteFromJSONTyped(json, false);
}

export function QuotasWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotasWrite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quotas': ((json['quotas'] as Array<any>).map(QuotaWriteFromJSON)),
    };
}

export function QuotasWriteToJSON(value?: QuotasWrite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quotas': ((value.quotas as Array<any>).map(QuotaWriteToJSON)),
    };
}

