/* tslint:disable */
/* eslint-disable */
/**
 * Unikorn Identity API
 * The Unikorn Identity API provides an OIDC compliant interface for use with all Unikorn services and proxies.  As it\'s intended use is for multi-tenant cloud deployments it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SystemOauth2ProviderRead } from './SystemOauth2ProviderRead';
import {
    SystemOauth2ProviderReadFromJSON,
    SystemOauth2ProviderReadFromJSONTyped,
    SystemOauth2ProviderReadToJSON,
} from './SystemOauth2ProviderRead';

/**
 * A list of system provided oauth2 providers.
 * @export
 * @interface SystemOauth2Providers
 */
export interface SystemOauth2Providers extends Array<SystemOauth2ProviderRead> {
}

/**
 * Check if a given object implements the SystemOauth2Providers interface.
 */
export function instanceOfSystemOauth2Providers(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SystemOauth2ProvidersFromJSON(json: any): SystemOauth2Providers {
    return SystemOauth2ProvidersFromJSONTyped(json, false);
}

export function SystemOauth2ProvidersFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemOauth2Providers {
    return json;
}

export function SystemOauth2ProvidersToJSON(value?: SystemOauth2Providers | null): any {
    return value;
}

