/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceWriteMetadata } from './ResourceWriteMetadata';
import {
    ResourceWriteMetadataFromJSON,
    ResourceWriteMetadataFromJSONTyped,
    ResourceWriteMetadataToJSON,
} from './ResourceWriteMetadata';
import type { UserSpec } from './UserSpec';
import {
    UserSpecFromJSON,
    UserSpecFromJSONTyped,
    UserSpecToJSON,
} from './UserSpec';

/**
 * A user create/update object.
 * @export
 * @interface UserWrite
 */
export interface UserWrite {
    /**
     * 
     * @type {ResourceWriteMetadata}
     * @memberof UserWrite
     */
    metadata?: ResourceWriteMetadata;
    /**
     * 
     * @type {UserSpec}
     * @memberof UserWrite
     */
    spec: UserSpec;
}

/**
 * Check if a given object implements the UserWrite interface.
 */
export function instanceOfUserWrite(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "spec" in value;

    return isInstance;
}

export function UserWriteFromJSON(json: any): UserWrite {
    return UserWriteFromJSONTyped(json, false);
}

export function UserWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWrite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': !exists(json, 'metadata') ? undefined : ResourceWriteMetadataFromJSON(json['metadata']),
        'spec': UserSpecFromJSON(json['spec']),
    };
}

export function UserWriteToJSON(value?: UserWrite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': ResourceWriteMetadataToJSON(value.metadata),
        'spec': UserSpecToJSON(value.spec),
    };
}

