/* tslint:disable */
/* eslint-disable */
/**
 * Identity API
 * The Identity API provides an OIDC compliant interface for use with all official and 3rd party services and proxies.  As its intended use is for multi-tenant cloud deployments, it acts as an aggregation layer for other 3rd party OIDC services, dispatching login requests to the required OIDC backend.  Token introspection forms the basis of role based access control across all APIs.  For security purposes, access tokens and refresh tokens are limited to a single session per client, thus if they are being consumed by a horizontally scalable platform care must be taken to ensure token rotation is handled atomically by a single process, and the tokens are distributed to each service instance synchronously.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A userinfo POST request.
 * @export
 * @interface UserinfoRequestOptions
 */
export interface UserinfoRequestOptions {
    /**
     * The oauth2 access token.
     * @type {string}
     * @memberof UserinfoRequestOptions
     */
    accessToken?: string;
}

/**
 * Check if a given object implements the UserinfoRequestOptions interface.
 */
export function instanceOfUserinfoRequestOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserinfoRequestOptionsFromJSON(json: any): UserinfoRequestOptions {
    return UserinfoRequestOptionsFromJSONTyped(json, false);
}

export function UserinfoRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserinfoRequestOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
    };
}

export function UserinfoRequestOptionsToJSON(value?: UserinfoRequestOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
    };
}

